# Use the latest official Nginx image as the base image.
FROM nginx:latest

# Copy the custom Nginx configuration file "proxy.conf" from your local directory to the container.
# This file will be used as the default Nginx configuration.
COPY proxy.conf /etc/nginx/conf.d/default.conf